export default [
  "What is the name of this venue?",
  "What is the address of this venue?",
  "What is the phone number of this venue?",
  "What is the email address of this venue?",
  "What is the website of this venue?",
  "Is Bottom Lounge an all-ages venue?",
  "How old do I have to be to attend a show at Bottom Lounge?",
  "My nephew is underage for the concert in question, but I am old enough. Can I bring him?",
  "What is the capacity of this venue?",
  "What is the parking situation at this venue?",
  "What is the public transportation situation at this venue?",
  "What is the food and drink situation at this venue?",
  "What is the smoking situation at this venue?",
  "What is the coat check situation at this venue?",
  "What is the bathroom situation at this venue?",
  "What is the accessibility situation at this venue?",
  "Is the space available for private events?",
  "How do I get my band booked at this venue?",
  "The show is sold out. Can I still get tickets?",
];
